<a href="https://colab.research.google.com/github/aljebraschool/Machine_Learning_A_Z_Basic/blob/main/Copy_of_artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
column_to_encode = [1, 2]
encoder = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), column_to_encode)], remainder='passthrough')

X = encoder.fit_transform(X)

print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_test.shape)

(2000, 13)


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
from tensorflow.keras.models import Sequential

model = Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
from tensorflow.keras.layers import Dense, Input

# layers = [
#      Dense(units = 6, activation = 'relu', name = 'layer1')
# ]

### Adding the second hidden layer

In [ ]:
# layers = [
#      Dense(units = 6, activation = 'relu', name = 'layer1'),

#      Dense(units = 6, activation = 'relu', name = 'layer1')
# ]

### Adding the output layer

In [ ]:
layers = [


     Dense(units = 6, activation = 'relu'),

     Dense(units = 12, activation = 'relu'),

     Dense(units = 1, activation = 'sigmoid')
]

In [ ]:
for layer in layers:
  model.add(layer)

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
model.compile(optimizer='adam', metrics = 'accuracy', loss = 'binary_crossentropy')

### Training the ANN on the Training set

In [ ]:
model.fit(X_train, y_train, batch_size= 32, epochs =100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7800
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4639 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4431 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4306 - accuracy: 0.8026
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4226 - accuracy: 0.8196
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4168 - accuracy: 0.8246
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4131 - accuracy: 0.8267
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4102 - accuracy: 0.8284
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4080 - accuracy: 0.8295
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4064 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [ ]:
print(model.predict(sc.transform([[1, 0, 0, 600, 1, 0, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 119ms/step
[[False]]


**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_hat = model.predict(X_test)
y_hat = (y_hat > 0.5)
print(np.concatenate((y_hat.reshape(len(y_hat),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 5ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

confusion_matrix(y_test, y_hat)

array([[1513,   82],
       [ 198,  207]])

In [ ]:
accuracy_score(y_test, y_hat)

0.86